# Generated by Django 4.2 on 2023-04-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_info',
            name='files',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
