# Generated by Django 4.2 on 2023-04-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_alter_event_info_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_info',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
